export type {
  Achievement,
  BlogPost,
  Certification,
  CVData,
  Experience,
  Profile,
  Project,
  ProjectCategory,
  Skill,
  SkillCategory,
  SocialLink,
  Stat,
  Testimonial,
} from '@web-cv-services/shared-types';
